// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintO;

#nullable disable

namespace PrintOSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250709123345_Figurine_variation_separate_sku")]
    partial class Figurine_variation_separate_sku
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("PrintO.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("authorUserId")
                        .HasColumnType("int");

                    b.Property<string>("contentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fileType")
                        .HasColumnType("int");

                    b.Property<long>("length")
                        .HasColumnType("bigint");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<DateTime>("uploadDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("authorUserId");

                    b.HasIndex("productId");

                    b.ToTable("files");
                });

            modelBuilder.Entity("PrintO.Models.FileTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("color")
                        .HasColumnType("int");

                    b.Property<int>("fileId")
                        .HasColumnType("int");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("fileId");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("PrintO.Models.ImageReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("fileId")
                        .HasColumnType("int");

                    b.Property<int>("index")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("fileId");

                    b.HasIndex("productId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("PrintO.Models.InvitationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("used")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("usedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("usedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("usedByUserId");

                    b.ToTable("invitationTokens");
                });

            modelBuilder.Entity("PrintO.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("importance")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.HasKey("Id");

                    b.HasIndex("productId");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("PrintO.Models.Products.Figurine.FigurineReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productId");

                    b.ToTable("figurines");
                });

            modelBuilder.Entity("PrintO.Models.Products.Figurine.FigurineVariation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<uint?>("averageHeightMm")
                        .HasColumnType("int unsigned");

                    b.Property<int>("color")
                        .HasColumnType("int");

                    b.Property<uint?>("depthMm")
                        .HasColumnType("int unsigned");

                    b.Property<int>("figurineId")
                        .HasColumnType("int");

                    b.Property<uint?>("heightMm")
                        .HasColumnType("int unsigned");

                    b.Property<int>("integrity")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint?>("maxHeightMm")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("minHeightMm")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("minimalPriceRub")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong>("priceBeforeSaleRub")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("priceRub")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("quantity")
                        .HasColumnType("int unsigned");

                    b.Property<int?>("scale")
                        .HasColumnType("int");

                    b.Property<string>("separateSKU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("weightGr")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("widthMm")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("figurineId");

                    b.ToTable("figurineVariations");
                });

            modelBuilder.Entity("PrintO.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<uint?>("ozonIntegrationVersion")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("productVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("series")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("storeId")
                        .HasColumnType("int");

                    b.Property<uint?>("wildberriesIntegrationVersion")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("yandexIntegrationVersion")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("storeId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("PrintO.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("stores");
                });

            modelBuilder.Entity("PrintO.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("selectedStoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("selectedStoreId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrintO.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("StoreUser", b =>
                {
                    b.Property<int>("membersId")
                        .HasColumnType("int");

                    b.Property<int>("membershipsId")
                        .HasColumnType("int");

                    b.HasKey("membersId", "membershipsId");

                    b.HasIndex("membershipsId");

                    b.ToTable("StoreUser");
                });

            modelBuilder.Entity("PrintO.Models.File", b =>
                {
                    b.HasOne("PrintO.Models.User", "authorUser")
                        .WithMany()
                        .HasForeignKey("authorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintO.Models.Products.Product", "product")
                        .WithMany("files")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("authorUser");

                    b.Navigation("product");
                });

            modelBuilder.Entity("PrintO.Models.FileTag", b =>
                {
                    b.HasOne("PrintO.Models.File", "file")
                        .WithMany("tags")
                        .HasForeignKey("fileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("file");
                });

            modelBuilder.Entity("PrintO.Models.ImageReference", b =>
                {
                    b.HasOne("PrintO.Models.File", "file")
                        .WithMany()
                        .HasForeignKey("fileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintO.Models.Products.Product", "product")
                        .WithMany("images")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("file");

                    b.Navigation("product");
                });

            modelBuilder.Entity("PrintO.Models.InvitationToken", b =>
                {
                    b.HasOne("PrintO.Models.User", "usedByUser")
                        .WithMany()
                        .HasForeignKey("usedByUserId");

                    b.Navigation("usedByUser");
                });

            modelBuilder.Entity("PrintO.Models.Note", b =>
                {
                    b.HasOne("PrintO.Models.Products.Product", "product")
                        .WithMany("notes")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("PrintO.Models.Products.Figurine.FigurineReference", b =>
                {
                    b.HasOne("PrintO.Models.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("PrintO.Models.Products.Figurine.FigurineVariation", b =>
                {
                    b.HasOne("PrintO.Models.Products.Figurine.FigurineReference", "figurine")
                        .WithMany("variations")
                        .HasForeignKey("figurineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("figurine");
                });

            modelBuilder.Entity("PrintO.Models.Products.Product", b =>
                {
                    b.HasOne("PrintO.Models.Store", "store")
                        .WithMany("products")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("store");
                });

            modelBuilder.Entity("PrintO.Models.User", b =>
                {
                    b.HasOne("PrintO.Models.Store", "selectedStore")
                        .WithMany()
                        .HasForeignKey("selectedStoreId");

                    b.Navigation("selectedStore");
                });

            modelBuilder.Entity("StoreUser", b =>
                {
                    b.HasOne("PrintO.Models.User", null)
                        .WithMany()
                        .HasForeignKey("membersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintO.Models.Store", null)
                        .WithMany()
                        .HasForeignKey("membershipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrintO.Models.File", b =>
                {
                    b.Navigation("tags");
                });

            modelBuilder.Entity("PrintO.Models.Products.Figurine.FigurineReference", b =>
                {
                    b.Navigation("variations");
                });

            modelBuilder.Entity("PrintO.Models.Products.Product", b =>
                {
                    b.Navigation("files");

                    b.Navigation("images");

                    b.Navigation("notes");
                });

            modelBuilder.Entity("PrintO.Models.Store", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
